### ISSUE TITLE
Basic search next button is not working 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#103]
## steps
Click on application 
try to create basic search 
enter the inputs and try to click next button 
## Expected result 
System must allow user to click on next button 
## Current result
System doesn't allow user to click on next button 
## screenshot 
![image](https://user-images.githubusercontent.com/46775670/143820631-fb9a6792-898a-41f4-ad80-37237dfb2737.png)

**Comment by prakash-kandasamy** [comment]
due to deployment issue happened and fixed by redeployment.

**Comment by Devikak7** [comment]
closing this issue
