### ISSUE TITLE
application scroll - repeating the application while scrolling down 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#104]
## steps
Try to scroll the page slow

## Expected result 
system must not show the application repeated
## Current result
System show the application repeated 
## screenshot 
![image](https://user-images.githubusercontent.com/46775670/143820772-556e460f-bb9e-438b-bd01-d90b29ebaa78.png)

**Comment by prakash-kandasamy** [comment]
issue in scroll event and fixed it.
