### ISSUE TITLE
Delete Data - while trying to delete the data for application without data in application Error message must be show proper 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#106]
## steps
Login sysadmin
Create application without data 
Now try to  delete the data for application when there is no data 
## Expected result 
System must show error message , when there is no data to delete 
## Current result
If there is not data to delete , it show data deleted successfully 
## screenshot 
![image](https://user-images.githubusercontent.com/46775670/144175678-cff4842a-7666-449e-8356-803bde1abf1b.png)

**Comment by Devikak7** [comment]
retested case
create a application without data 
now  select  and try to delete the data  it shows UI message as Background jobs scheduled while the job is inprogress
try to delete the application 
the job where the entry added in background job is getting deleted

**Comment by P3IND0167** [comment]
Issue resolved working as Expected
