### ISSUE TITLE
Application creation - while trying to click on application creation button it is not creating application 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#108]
## steps
Login sysadmin
Create application
add the data and now click storage 
Click create application button  
## Expected result 
System must allow user to create application 
## Current result
System doesn't allow user to create application, and clear the tab added already 
## screenshot 
![image](https://user-images.githubusercontent.com/46775670/144183115-17b785d1-590f-4af7-bcdc-557f698067ea.png)

![image](https://user-images.githubusercontent.com/46775670/144183096-c531f156-35ee-4f6f-8504-91d9bd484765.png)
![image](https://user-images.githubusercontent.com/46775670/144183141-6b4618ca-ffb2-4415-a574-ac65efa94dde.png)

**Comment by Divyapriya06** [comment]
<img width="1440" alt="Screenshot 2021-12-14 at 10 52 28 AM" src="https://user-images.githubusercontent.com/83642259/145938799-ca53b401-1917-40cf-ae54-925b4776caa3.png">

**Comment by Devikak7** [comment]
working fine
