### ISSUE TITLE
Application - while trying to delete the incomplete  application , user is unable to delete the application 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#110]
## steps 
Login sysadmin
create a application without uploading metadata file
Now try to delete the application once created
## Expected result 
System must allow user to delete the application if metadata is not uploaded 
## Current result
System shows  doesn't show any error message , instead showing 500 internal server error message
## screenshot 

![image](https://user-images.githubusercontent.com/46775670/144222891-74eb9962-5918-4421-8f4f-879ce8cc2da3.png)

{"timestamp":"01-12-2021 10:52:26","status":500,"message":null,"error":"Error occurred","path":"/core-system/application/c6169597-3c5f-487a-8484-7cbd797135fc"}

**Comment by KowsalyaChandran** [comment]
<img width="1349" alt="Screenshot 2021-12-10 at 10 45 03 AM" src="https://user-images.githubusercontent.com/83642018/145521506-e56c3a2b-fe03-4cb8-8b6d-8b406c504022.png">
<img width="1300" alt="Screenshot 2021-12-10 at 10 44 34 AM" src="https://user-images.githubusercontent.com/83642018/145521528-d398dd6c-800f-4a54-a32e-68698f548c5c.png">
<img width="1371" alt="Screenshot 2021-12-10 at 10 45 54 AM" src="https://user-images.githubusercontent.com/83642018/145521548-ac8be4de-9a1e-4586-965a-35b0a215aa8b.png">

**Comment by Devikak7** [comment]
working now
