### ISSUE TITLE
Application creation - taking long time to create and UI message is not showing for application created successfully 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#114]
## steps
Login sysadmin 
Create application enter the data 
Click on metadata upload the metadata file
Create the retention policy 
## Expected result 
System must create the application and show the UI message 
## Current result
System doesn't show the message application created successfully and it  take long time to load 
## screenshot 
![image](https://user-images.githubusercontent.com/46775670/145155154-63f35cd2-5cd9-4ba5-a30a-513a74574bbf.png)

**Comment by Divyapriya06** [comment]
<img width="1440" alt="Screenshot 2021-12-13 at 4 36 16 PM" src="https://user-images.githubusercontent.com/83642259/145803237-6cbb9fcb-6127-40a3-b580-6f1d771db30f.png">
