### ISSUE TITLE
Search -   while enabling hidden field for forms it is listing the container in search screen 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#115]
## steps
Login sysadmin
Create a search for basic search 
Click on container and add a form enable the hidden field radio button 
## Expected result 
system must not show the data when field  is enabled 
## Current result
System shows the field when hidden field is enabled 
## screenshot 
![image](https://user-images.githubusercontent.com/46775670/145160067-e5d2e65c-e609-4ead-b56f-bbb6c76db09b.png)

![image](https://user-images.githubusercontent.com/46775670/145160103-bad737a4-8f91-4e7e-ab29-b829a5002eea.png)

Reference from IA
![image](https://user-images.githubusercontent.com/46775670/145160154-f2c78c9c-7f5b-43e8-8c77-99c480006c88.png)

![image](https://user-images.githubusercontent.com/46775670/145160206-eaae0aa5-591d-46eb-86fe-278abce87531.png)

**Comment by Divyapriya06** [comment]
[](url
<img width="1440" alt="Screenshot 2021-12-13 at 5 50 59 PM" src="https://user-images.githubusercontent.com/83642259/145811432-2e83bd42-820e-425f-9759-0b0aff9497bb.png">
)

**Comment by Divyapriya06** [comment]
<img width="1440" alt="Screenshot 2021-12-13 at 5 52 38 PM" src="https://user-images.githubusercontent.com/83642259/145811526-dbaeb118-90d2-4654-b0d2-218ee068f0be.png">

**Comment by kilam005** [comment]
@Devikak7 @Divyapriya06 
![image](https://user-images.githubusercontent.com/18091138/145937747-262f3270-2264-4304-9f3a-8dba21944c1d.png)
