### ISSUE TITLE
Job - Refresh Metrics is showing download button 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#116]
![image](https://user-images.githubusercontent.com/46775670/148504135-85d455f3-b163-4a7a-9c9f-0bce36a1fc6c.png)

**Comment by PriyaJp3** [comment]
Download options are removed now. export and download actions are handled as background jobs

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/155114610-a123c628-a69f-4c80-a72c-ceda8a7656f9.png)
refresh metric jobs getting failed

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/161975112-04abe0e6-32be-436d-b9f0-b88c465b10eb.png)
