### ISSUE TITLE
import - application while trying to edit the application application type is not listing 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#122]
## steps
Login sysadmin
create application export the application 
now delete the existing application 
import the same application and edit the app info 
## Expected result 
system must show the application type 
## Current result
System doesn't show the application type 
## screenshot 
![image](https://user-images.githubusercontent.com/46775670/153855783-20cef88d-d908-452d-9eba-c0fd58902443.png)

**Comment by Divyapriya06** [comment]
[](url
<img width="1440" alt="Screenshot 2022-04-06 at 5 26 07 PM" src="https://user-images.githubusercontent.com/83642259/161969470-fbb018c7-6c20-431c-b137-36f9d13dc9ed.png">
)

**Comment by P3IND0167** [comment]
Server- http://192.168.1.180:4081

Issue Resolved:  Testimport application imported and tested, application type displaying as per below screenshot

![image](https://user-images.githubusercontent.com/103109787/161986392-40fa33aa-6dd8-4b21-8221-720a69342a08.png)
