### ISSUE TITLE
adhoc search - link shows 500 internal server error

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#125]
## steps 
Login sysadmin
Select CLAIMS_SYS_TEST
Adhoc search 
Click on link memeber 
## Expected result 
System must show  error message in UI 
## Current result
System show 500 in console error 
## screenshot 
![image](https://user-images.githubusercontent.com/46775670/155106981-ea255561-3d08-4991-9460-f9d7813cc656.png)

![image](https://user-images.githubusercontent.com/46775670/155104184-18f75e26-1517-4fd1-8a8a-2d70c5b78c0b.png)

**Comment by P3IND0167** [comment]
Adhoc Search - Link working as Expected
