### ISSUE TITLE
blob data not listing showing error 

### ISSUE THREAD

**Issue by Devikasarath77** [P3-Core-Dev-Team/LWA-issue-tracker#127]
## steps
Login sysadmin
Click on ppl_soft application
Select use-yearend table data and try to select the attachment 
## Expected result 
System must show the attachment 
## Current result
system show error message 
## screenshot 
![image](https://user-images.githubusercontent.com/47816479/155270558-addb6a5a-db23-4bb8-af57-971cc2e79c63.png)

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/155270975-babf0e71-b62c-4505-b804-34bde91ec27f.png)

search screen - adhoc search

**Comment by Devikak7** [comment]
tested with fairview and dc server
