### ISSUE TITLE
Application category manage shows error 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#128]
http://13.234.240.186:4081/applications
## steps
Login sysadmin
Click on the category 
## Expected result 
system must show the categories added
## Current result
System shows error message 
## screenshot 

![image](https://user-images.githubusercontent.com/47816479/155937055-dc44c3ab-f4c4-410e-806b-bc11803a7aa8.png)

**Comment by P3IND0167** [comment]
issue solved tested in http://192.168.1.180:4081

Please find the below screenshot for reference
![image](https://user-images.githubusercontent.com/103109787/161977424-b19ef2ef-4ab5-4e15-8574-a2d33de5a68e.png)
