### ISSUE TITLE
Application delete data shows error message 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#129]
## server
http://13.234.240.186:4081/app-table/c0a57753-cd7b-44df-ae31-80cd684e1208
## steps
Login sysadmin
Click application CLAIMS_SYSTEM
Select the table address 
Select delete data 
 
## Expected result 

System must allow user to delete the data / must show error message 
## Current result
System shows error message 
## screenshot 

![image](https://user-images.githubusercontent.com/46775670/155937793-41977158-1d63-4893-b452-0b0efc790b0b.png)
![image](https://user-images.githubusercontent.com/46775670/155937823-0bb80143-bd9c-4ee5-bda8-ba1763f37a15.png)

**Comment by sowndaryameiyazhagan** [comment]
@PriyaJp3 this instance is not available now
