### ISSUE TITLE
Export application - retention applied to application is not listing while the application is imported 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#130]
## steps
Login sysadmin
Export the application Claim-retest
now import the same application 
## Expected result 
If retention already exist with the application it must list 
## Current result
Retention is not getting exported 
## screenshot 
![image](https://user-images.githubusercontent.com/46775670/156107760-17f94c3c-4e62-4f9c-ac0e-7a52b1f29812.png)

![image](https://user-images.githubusercontent.com/46775670/156107773-5e388a9e-ccda-471e-8448-c52478b19c09.png)

note; retention applied to the table in the application

**Comment by PriyaJp3** [comment]
Compliance details will not be imported. 

Only metadata & searches will be imported

**Comment by P3IND0167** [comment]
Closing the issue as per the comment
