### ISSUE TITLE
Application unable to delete show no  value present error 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#131]
## steps
Create application 
try to select delete data and then delete application 
## Expected result 
System must delete the application 
## Current result
System shows error message 
## screenshot
![image](https://user-images.githubusercontent.com/46775670/158363859-864693ab-1cf4-47b9-8b1c-3f97f690a626.png)

**Comment by P3IND0167** [comment]
Working as Expected
