### ISSUE TITLE
ingestion - need to add exception it is not listing failure message when data mismatch

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#136]
# module : ingestion 
# server : dc and fair view 
https://archon-archive-dc.platform3solutions.com:4082
# steps: 
Create application and upload metadata file 
Try to ingest data
 metadata is having 4 cloumns and the ingested data is having 3 columns 

# expected result 
system must show error in ingestion tacker
# Current result 
System doesnt show any data in ingestion tracker 

#screenshot 

![image](https://user-images.githubusercontent.com/46775670/161705507-8d698cc3-2c93-4b7c-a86b-fcfa4fc32a83.png)
![image](https://user-images.githubusercontent.com/46775670/161705559-7c14b577-accb-4185-9685-716424cf7c02.png)

**Comment by P3IND0167** [comment]
Issue resolved working as Expected
