### ISSUE TITLE
 Retention Policy - unable to add data for  Retention Policy

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#14]
## steps to reproduce
Login sysadmin/sysadmin
Select compliance
add retention  fill the fields 
and save the data
## expected result 
system must allow user to save the data 
## current result 
System doesn't allow user to save the data 
## screenshot

![image](https://user-images.githubusercontent.com/46775670/125567710-9c676566-57f4-490c-8bc5-fec1d93bca17.png)
{"timestamp":"2021-07-14T05:32:55.228+00:00","status":500,"error":"Internal Server Error","exception":"org.springframework.dao.DataIntegrityViolationException","message":"could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement","path":"/core-system/system-management/compliance-management/retention-policy/d5e717b6-4852-408a-bfc1-7529f16121d6"}

**Comment by ashoksri0** [comment]
now issues solved need to add test cases

**Comment by Devikak7** [comment]
worked fine
