### ISSUE TITLE
Metadata creation - without adding the metadata mandatory field user is able to  create column

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#2]
## server details
http://192.168.1.28:4081/metadata/create/5246911e-fdb5-4ae1-a74a-0ccdc43afae9
## steps to reproduce
Login as syadmin
Create application 
Create metadata file 
Create a new metadata file with column
## expected result 
System must not allow user to create without the mandatory field 
## current result 
System allow user to create 
## screenshot

![image](https://user-images.githubusercontent.com/46775670/124577076-8e494c00-de6a-11eb-8664-23f9d729ab62.png)

**Comment by ashoksri0** [comment]
default we have String in type  
![Selection_016](https://user-images.githubusercontent.com/14317595/124940764-dfeb0580-e027-11eb-9d1a-49bc67117fb6.png)

**Comment by Devikak7** [comment]
working fine
