### ISSUE TITLE
upload  metadata - unable to upload metadata file 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#23]
## steps to reproduce
Login sysadmin
Create application try to upload json metadata file 
## expected result 
System must allow user to upload metadata file  
## current result 
System shows error message 
## screenshot

![image](https://user-images.githubusercontent.com/46775670/126742885-ebd399e9-7600-4410-bf32-16c6c5e93e5c.png)

**Comment by ashoksri0** [comment]
upload the related file

**Comment by ashoksri0** [comment]
fixed and will reflect in next deployment

**Comment by ashoksri0** [comment]
unit test pennding

**Comment by Devikak7** [comment]
fixed
