### ISSUE TITLE
metadata upload - add metadta without db name 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#27]
.Uploaded metadata file without adding the database name 

{"timestamp":"26-07-2021 07:18:56","status":500,"message":"Unexpected character ('{' (code 123)): was expecting double-quote to start field name\n at [Source: (FileInputStream); line: 10, column: 22] (through reference chain: com.p3.lwa.baseservice.application.metadata.lwa.ApplicationMetadataBean[\"metadataEntity\"]->com.p3.lwa.baseservice.application.metadata.lwa.MetadataEntity[\"schemaMetadataList\"]->java.util.ArrayList[0]->com.p3.lwa.baseservice.application.metadata.lwa.SchemaMetadata[\"tableMetadataList\"]->java.util.ArrayList[0])","error":"Error occurred","path":"/core-system/application/metadata"}

**Comment by Devikak7** [comment]
[nodata.txt](https://github.com/P3-Core-Dev-Team/LWA-issue-tracker/files/6884136/nodata.txt)
attaching json as txt file

**Comment by ashoksri0** [comment]
fixed for the empty values

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/127507755-f1f263fb-718b-4afc-b650-fd83b26b12ff.png)
[nodbname.txt](https://github.com/P3-Core-Dev-Team/LWA-issue-tracker/files/6901158/nodbname.txt)
not working , expected to show proper error if not supporting

**Comment by Devikak7** [comment]
closed
