### ISSUE TITLE
Metadata - upload metadata - UI issue 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#28]
[test_metadata.txt](https://github.com/P3-Core-Dev-Team/LWA-issue-tracker/files/6890996/test_metadata.txt)
 not listing the detail

**Comment by Devikak7** [comment]
local code issue

**Comment by ashoksri0** [comment]
in the test also its working same as bug
[nodata.txt](https://github.com/P3-Core-Dev-Team/LWA-issue-tracker/files/6892557/nodata.txt)

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/127317478-faf4fdf8-45b7-4dfc-9033-bdb81c8a5cc9.png)

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/127659255-24797826-7b92-45d8-a302-3379abf18c61.png)
