### ISSUE TITLE
Accesstoken need to be cleared 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#3]
![image](https://user-images.githubusercontent.com/46775670/124869909-86f77f00-dfdf-11eb-8ce2-7cc40296c850.png)
![image](https://user-images.githubusercontent.com/46775670/124869990-a5f61100-dfdf-11eb-88c1-d05d33114742.png)

**Comment by ashoksri0** [comment]
hold on this issues we need to change it with oauth

**Comment by Devikak7** [comment]
as per @ashoksri0  issue is onhold status
