### ISSUE TITLE
added metadata is not listing the data as per the  database name is selected 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#37]
## steps to reproduce
Login sysadmin
Select the upload metadata and select the database name 

## expected result 
System  must shows table as per the selected db name 
## current result 
System shows error message 
## screenshot

![image](https://user-images.githubusercontent.com/46775670/132488715-ffa81742-fb63-40fe-8533-3360e114fbba.png)

**Comment by ashoksri0** [comment]
this issues is because of the server database has some connection problem 
you can close this
