### ISSUE TITLE
while trying to edit the add metadata file system shows no internet connection as error message 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#39]
## module
Metadata upload 
# server  test server 
# steps
Login sysadmin
Create the application
Update the metadata file
Select the table and click on edit button 
# details
# screenshot 
![image](https://user-images.githubusercontent.com/46775670/133762179-1c495e14-7be8-4473-893e-ad180f904db1.png)

**Comment by ashoksri0** [comment]
ignore this error and close this issue
