### ISSUE TITLE
Application - unable to delete the application showing error message 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#4]
## steps to reproduce
Login sysadmin/sysadmin
Select the movie application 
Select the delete - and try to delete the application 
## expected result 
System must not show error message 
## current result 
System must show error message 
## screenshot

![image](https://user-images.githubusercontent.com/46775670/124870414-52d08e00-dfe0-11eb-881e-b66d23273a4e.png)

**Comment by ashoksri0** [comment]
while deleting application  its does not have any applied retention, hold and any data including metadata  ut now metadata delete is not implemented so leave that

**Comment by ashoksri0** [comment]
invalid issues

**Comment by Devikak7** [comment]
closing the issue as per the comment
