### ISSUE TITLE
System shows error message while deleting the data 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#41]
# module Metadata upload
# server  test server 
# steps
Login sysadmin
Upload the metadata file  for the application 
now delete the uploaded metadata file 
# details
# Expected result
System must not show error while trying to delete all the data presented in the application 
# current result 
System shows error message 
# screenshot 

![image](https://user-images.githubusercontent.com/46775670/133794599-cb76806e-b25a-4152-9a23-617b4d4fb12d.png)

**Comment by Divyapriya06** [comment]
<img width="1440" alt="Screenshot 2021-11-24 at 1 30 47 PM" src="https://user-images.githubusercontent.com/83642259/143198175-ecc59971-96cf-4e57-9b64-719e63e0a4fb.png">
