### ISSUE TITLE
application - edit application - while user is enabling the access mode it is resetted as disabled 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#55]
# module application edit 
# server  test server 
# steps
Login sysadmin/Sysadmin
Click application
Click on application info
Click on access mode 
try to enable the access mode
# Expected result
System must show access mode if the user enabled it 
# current result 
System doesn't show the access mode if the user enabled it is getting disabled
# screenshot 
![image](https://user-images.githubusercontent.com/46775670/135578466-70854881-7211-4f73-9ddf-98cfdbe7c75d.png)
![image](https://user-images.githubusercontent.com/46775670/135578507-5e72643f-af0d-4d31-8dfb-7ffd15ea0f4e.png)

**Comment by yowanrajan** [comment]
@ashoksri0 this enhancement work pls check and update ji

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/141086134-b35440d2-532d-4fd2-8f2e-ad6a52713ca1.png)
