### ISSUE TITLE
application - filter expected to  have a reset button 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#56]
#module  application
# server  test server 
# steps
login sysadmin
try to filter the category 

# current result
While user is trying to filter the category it show the data unable to reset the option selected 
# expected result
If user need to cancel the filter category expected to  have reset button else while user is trying to select home button it should list all the application 
#screenshot
![image](https://user-images.githubusercontent.com/46775670/135578961-4e452ed7-e28d-4251-9784-f4483fafad9b.png)
![image](https://user-images.githubusercontent.com/46775670/135579275-89b55460-5263-4e97-8ea3-884928d85a85.png)

**Comment by PriyaJp3** [comment]
Category has option "ALL". If user wants to reset the category, can choose all to list all application listing.

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/136735601-d86cee9f-df17-449c-9e96-66463e4da3f9.png)
