### ISSUE TITLE
Metadata - editing the column shows error message  alphabet and _  only allowed 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#6]
## steps to reproduce
Login sysadmin
Select the application as case1
Edit the metadata uploaded 
Try to add column tag test data
## expected result 
System must not  show an error
## current result 
System shows error message 
## screenshot
![image](https://user-images.githubusercontent.com/46775670/124882279-d775d900-dfed-11eb-8c33-c211521335a8.png)

Note : metadata is allowing user to upload the  column with space 
![image](https://user-images.githubusercontent.com/46775670/124882422-fd02e280-dfed-11eb-8090-de9778910ef4.png)
![image](https://user-images.githubusercontent.com/46775670/124882456-0429f080-dfee-11eb-83fe-dce690cc919e.png)

**Comment by yowanrajan** [comment]
Issue fixed
url http://192.168.1.58:4081/

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/126794928-9baa47c6-fd53-4516-ae11-9b06c58a4fdb.png)
