### ISSUE TITLE
Search - Tag are not listing in search screen 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#60]
![image](https://user-images.githubusercontent.com/46775670/136036133-19496d4d-06a8-4fd7-a8b4-1e4fe293342d.png)

**Comment by Devikak7** [comment]
not listing please check and assign the issue

**Comment by PriyaJp3** [comment]
Manage categories screen in development

**Comment by kilam005** [comment]
@VikramSelvadurai  what is the status of this.
If issue is fixed. Added comments and send for retest

@PriyaJp3 follow up

**Comment by VikramSelvadurai** [comment]
issue fixed , move to deployment

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/147336039-b8f9af15-6dc3-4604-86bb-6befd035c8d8.png)
![image](https://user-images.githubusercontent.com/46775670/147336094-7a022c59-0e06-4d71-a11f-9b0455ec91eb.png)
