### ISSUE TITLE
Search datatype - for datetime field control type is listing as single 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#61]
# module search basic search 
# server  test server 
# steps
Login as sysadmin
Click on application 
Click on search
Click on basic search select the column with datetime datatype 

# Expected result

System must show datetime as control type 
# current result 
It is listing single 
# screenshot 
![image](https://user-images.githubusercontent.com/46775670/136361601-5da61308-b553-4496-b0e5-51a3240e517d.png)

**Comment by prakash-kandasamy** [comment]
This select is indicating the single or multiple date. So it showing the Single for field control type as per date datatype.

**Comment by Devikak7** [comment]
as per the above comment closed this issue
