### ISSUE TITLE
UI issues 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#62]
![image](https://user-images.githubusercontent.com/46775670/136361358-72f93f68-7199-427e-80ee-d7b9005e045d.png)

done

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/136389252-4990ddc9-c321-4787-bf17-62570c4bec83.png)

Expecting to show  given app  name as application name

**Comment by PriyaJp3** [comment]
Except the container issue, others fixed. will work on container issue later
