### ISSUE TITLE
Adhoc search - suggestion  to show preview of the query added 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#65]
![image](https://user-images.githubusercontent.com/46775670/136383861-c9a1aa29-0e34-4d32-98ec-2d5bd5879d32.png)
![image](https://user-images.githubusercontent.com/46775670/136383926-fb8f5780-e857-47c3-90b8-b3ed30844337.png)

## note : 
when user is trying give more than 25 condition in search while applying and / or condition it will be difficult for the user to find where the condition is applied

**Comment by kilam005** [comment]
Will take this up soon.

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/147435511-e6071f6b-6ead-4573-9407-39b3828bf0f1.png)
