### ISSUE TITLE
suggestion - adhoc search - filter Condition to apply for 2 tables 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#70]
# module adhoc search 
# server  test server 
# steps 
login sysadmin
Click claimsys application 
Select the adhoc search 

# Expected result

user can create adhoc search with multiple table filter condition and create search screen 
# current result 
System can apply filter condition only for one table 
# screenshot 
![image](https://user-images.githubusercontent.com/46775670/136551308-c48d495a-1da5-47ee-838a-c88a12bc81d6.png)

**Comment by kilam005** [comment]
The functionality here is limited to one table only.
There will be a differnt process that will come in future to support multiple table (either from LWA or Archon side)

Please close this issue

**Comment by Devikak7** [comment]
as per comment closing this issue
