### ISSUE TITLE
adhoc search - filter condition are cases sensitive 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#71]
# module adhoc search 
# server  test server 
# steps
Login sysadmin
Click on application claim sys
Click adhoc search 
select table as address
Click on state as input = mo

# Expected result
System must show the data filtered 
# current result 
System doesnt show the data filtered 
# screenshot 

![image](https://user-images.githubusercontent.com/46775670/136551489-ff8b15a2-b746-4fbe-9624-2377b8477dff.png)
![image](https://user-images.githubusercontent.com/46775670/136551789-82867b21-3b4d-4c4c-9ed8-b606165afbca.png)

**Comment by PriyaJp3** [comment]
Issue exists in whole search part.closing this issue and have a common one .

**Comment by Devikak7** [comment]
tracked with issue 85
