### ISSUE TITLE
Cache entity gets duplicate values 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#87]
![image](https://user-images.githubusercontent.com/46775670/141447403-070547ac-45b2-4fa8-bb61-ff27b6d22b6e.png)

**Comment by siddhantp3s** [comment]
Happens due to separate cache configuration for local and server, because of which separate query ids get generated.

**Comment by kilam005** [comment]
This issue will not be replicatable in live environment. 
When we have a seperate machine dedicated for prod testing this can be rechecked.
