### ISSUE TITLE
Adhoc search - while trying to search the data with related table it shows error message 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#88]
# module adhoc search 
# server  Test server 
# steps
Login sysadmin
Claim sys application
Select adhoc search click on address table ,column as addr_id value = 90001
Click on the member link tab

# Expected result
System must show the data 
# current result 
System shows error message as search not performed 
# screenshot

**Comment by kilam005** [comment]
90001 is a Provider ID.
it wll show results when linked with provider search.

Member id starts from 100001
That is why no results showed up.

Recheck and close.
