### ISSUE TITLE
Metadata - Deleted column are listing  

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#9]
## steps to reproduce
Login sysadmin/Sysadmin
Select the case1 application
Select  metadata and 
click on  create metadata
Create new table and columns
Now try to delete the metadata column added 
## expected result 
System must delete the column
## current result 
System shows row deleted , but column is listing in the metadata 
## screenshot
![image](https://user-images.githubusercontent.com/46775670/124915400-1b2d0a80-e00f-11eb-98ad-bd2df6eccb8f.png)
![image](https://user-images.githubusercontent.com/46775670/124915428-24b67280-e00f-11eb-9095-4dd4bba342bb.png)
![image](https://user-images.githubusercontent.com/46775670/124915457-2e3fda80-e00f-11eb-89a3-f62e370051df.png)
![image](https://user-images.githubusercontent.com/46775670/124915474-3566e880-e00f-11eb-8b01-5c841d5ed7da.png)
![image](https://user-images.githubusercontent.com/46775670/124915520-431c6e00-e00f-11eb-9fd2-df2458e86b1b.png)

**Comment by ashoksri0** [comment]
its a normal flow

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/125771253-34f8dcd0-7ba1-41ff-8fa4-384d148b8a0e.png)
