### ISSUE TITLE
HOLD- while creating hold user is not adding the matter tab 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#90]
# module hold
# server  test server 
# steps
Login sysadmin
Click on Compliance
Select the  hold , set while creating hold user is not giving the matter field
# Expected result 
System must not show if user is not giving the input
# current result 
System shows the matter as Not applicable 
# screenshot 
![image](https://user-images.githubusercontent.com/46775670/141458320-3966e8aa-40e2-4ae6-b5f4-887b9434b786.png)

**Comment by PriyaJp3** [comment]
Added to backlog. Closing this for now.
