### ISSUE TITLE
Ingestion failure - 500 internal server Error 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#92]
Timestamp: "16-11-2021 09:55:47", status: 500,…}
error: "Error occurred"
message: "StatementCallback; uncategorized SQLException for SQL [select \"ADDR_ID\",\"IS_PROV\",\"ADDR_TYPE\",\"ADDRESS\",\"CITY\",\"STATE\",\"ZIP\",\"PHONE\",\"FAX\",\"EMAIL\" from iceberg.\"030a8224_7639_46ec_b8f9_d43e0dda67b2\".\"e61bf7ea_f340_46ba_b71d_359864bc3142\" limit 50]; SQL state [null]; error code [45]; Query failed (#20211116_095546_00048_hfqq5): line 1:98: Schema '030a8224_7639_46ec_b8f9_d43e0dda67b2' does not exist; nested exception is java.sql.SQLException: Query failed (#20211116_095546_00048_hfqq5): line 1:98: Schema '030a8224_7639_46ec_b8f9_d43e0dda67b2' does not exist"
path: "/core-system/application/database/schema/table/e61bf7ea-f340-46ba-b71d-359864bc3142/false/data"
status: 500
timestamp: "16-11-2021 09:55:47"

**Comment by Devikak7** [comment]
application name : TEST_CLAIMS
click the application name and select metadata 
Select the data

**Comment by Yuvaraj-P3** [comment]
@Devikak7 We have verified the issue with a new application. The issue occurs because of data wasn't ingested properly.
