### ISSUE TITLE
Search - not listing all the columns 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#95]
# module search 
# server  test server 
# steps
Select the application as TEST_soft
Select adhoc search 
give the search data as per the given screenshot below now click submit button 
# details
# Expected result
System must show all the data 
# current result 
System doesn't show all data in UI
# screenshot 
![image](https://user-images.githubusercontent.com/46775670/142817114-1a3044d9-a53a-40fb-a557-6b3c73d4070b.png)

![image](https://user-images.githubusercontent.com/46775670/142817168-448618df-b410-46c5-9405-b942420fe8be.png)

0: {setid: "BEL", absence_type: "001", absence_class: "VAC", descr: "Vacation", descrshort: "Vacation",…}
abs_entry_panel: "VAC"
abs_track_incident: "N"
abs_track_mat: "N"
absence_class: "VAC"
absence_image_ref: "VACATION"
absence_type: "001"
cert_period: 0
cert_period_type: "DAY"
cert_required: "N"
descr: "Vacation"
descrshort: "Vacation"
image_name: "VACATION"
lwa_id: "cf1f2d8c_d00b_46ca_8530_056708cc7347:0:c32d1d5a-4c26-4af7-9a99-24a89a5f363c"
mand_r_period_bel: 2
mandat_repl_bel: "N"
paid_unpaid_ind: "NA"
prolong_notif_bel: "N"
prolong_prob_bel: "Y"
prolong_prot_bel: "N"
setid: "BEL"

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/143009385-6c1153f3-86c8-4524-a17f-f7718f747d7d.png)

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/143011541-8806df0b-4ef1-4894-8d19-81d4d075e181.png)

**Comment by prakash-kandasamy** [comment]
![image](https://user-images.githubusercontent.com/79510599/143012075-fbe8d4e5-bf07-4b16-b9c0-df84c118ae87.png)


working fine.

**Comment by Devikak7** [comment]
working fine closed
