### ISSUE TITLE
Search - application link is not working 

### ISSUE THREAD

**Issue by Devikak7** [P3-Core-Dev-Team/LWA-issue-tracker#96]
# module search 
# server 
test server 
# steps
Login as sysadmin
Click TEST_SFT application
Select the search basic edit the data 
Now click on the result try to give the link for other application a claims_sys 
And save the search 
Now try to do search the data 
# details
# Expected result
System must show the added application
# current result 
System doesn't show the added application
# screenshot 

![image](https://user-images.githubusercontent.com/46775670/142819053-7edc078f-f5ff-49e8-b5f5-09d0c4093588.png)
![image](https://user-images.githubusercontent.com/46775670/142819085-d9af49b7-fb06-4c65-892e-c5b2b50067d0.png)

**Comment by Devikak7** [comment]
![image](https://user-images.githubusercontent.com/46775670/142819419-d9d83c25-e236-4ab6-bf9d-10f51b500ad3.png)

**Comment by kilam005** [comment]
@siddhantp3s what is the update on this issue

**Comment by siddhantp3s** [comment]
Going to check and resolve this now
